// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin

import (
	"server/api/admin"
)

type ControllerDicttype struct{}

func NewDicttype() admin.IAdminDicttype {
	return &ControllerDicttype{}
}

type ControllerDictdata struct{}

func NewDictdata() admin.IAdminDictdata {
	return &ControllerDictdata{}
}

type ControllerUser struct{}

func NewUser() admin.IAdminUser {
	return &ControllerUser{}
}

type ControllerLogin struct{}

func NewLogin() admin.IAdminLogin {
	return &ControllerLogin{}
}

type ControllerRole struct{}

func NewRole() admin.IAdminRole {
	return &ControllerRole{}
}

type ControllerAttachment struct{}

func NewAttachment() admin.IAdminAttachment {
	return &ControllerAttachment{}
}

type ControllerCrontab struct{}

func NewCrontab() admin.IAdminCrontab {
	return &ControllerCrontab{}
}

type ControllerMenu struct{}

func NewMenu() admin.IAdminMenu {
	return &ControllerMenu{}
}
