// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalPandaDictTypeDao is an internal type for wrapping the internal DAO implementation.
type internalPandaDictTypeDao = *internal.PandaDictTypeDao

// pandaDictTypeDao is the data access object for the table panda_dict_type.
// You can define custom methods on it to extend its functionality as needed.
type pandaDictTypeDao struct {
	internalPandaDictTypeDao
}

var (
	// PandaDictType is a globally accessible object for table panda_dict_type operations.
	PandaDictType = pandaDictTypeDao{
		internal.NewPandaDictTypeDao(),
	}
)

// Add your custom methods and functionality below.
