// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalPandaDictDataDao is an internal type for wrapping the internal DAO implementation.
type internalPandaDictDataDao = *internal.PandaDictDataDao

// pandaDictDataDao is the data access object for the table panda_dict_data.
// You can define custom methods on it to extend its functionality as needed.
type pandaDictDataDao struct {
	internalPandaDictDataDao
}

var (
	// PandaDictData is a globally accessible object for table panda_dict_data operations.
	PandaDictData = pandaDictDataDao{
		internal.NewPandaDictDataDao(),
	}
)

// Add your custom methods and functionality below.
