// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalPandaCrontabDao is an internal type for wrapping the internal DAO implementation.
type internalPandaCrontabDao = *internal.PandaCrontabDao

// pandaCrontabDao is the data access object for the table panda_crontab.
// You can define custom methods on it to extend its functionality as needed.
type pandaCrontabDao struct {
	internalPandaCrontabDao
}

var (
	// PandaCrontab is a globally accessible object for table panda_crontab operations.
	PandaCrontab = pandaCrontabDao{
		internal.NewPandaCrontabDao(),
	}
)

// Add your custom methods and functionality below.
