// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalPandaUserDao is an internal type for wrapping the internal DAO implementation.
type internalPandaUserDao = *internal.PandaUserDao

// pandaUserDao is the data access object for the table panda_user.
// You can define custom methods on it to extend its functionality as needed.
type pandaUserDao struct {
	internalPandaUserDao
}

var (
	// PandaUser is a globally accessible object for table panda_user operations.
	PandaUser = pandaUserDao{
		internal.NewPandaUserDao(),
	}
)

// Add your custom methods and functionality below.
