// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalPandaRoleMenuDao is an internal type for wrapping the internal DAO implementation.
type internalPandaRoleMenuDao = *internal.PandaRoleMenuDao

// pandaRoleMenuDao is the data access object for the table panda_role_menu.
// You can define custom methods on it to extend its functionality as needed.
type pandaRoleMenuDao struct {
	internalPandaRoleMenuDao
}

var (
	// PandaRoleMenu is a globally accessible object for table panda_role_menu operations.
	PandaRoleMenu = pandaRoleMenuDao{
		internal.NewPandaRoleMenuDao(),
	}
)

// Add your custom methods and functionality below.
