// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalPandaMenuDao is an internal type for wrapping the internal DAO implementation.
type internalPandaMenuDao = *internal.PandaMenuDao

// pandaMenuDao is the data access object for the table panda_menu.
// You can define custom methods on it to extend its functionality as needed.
type pandaMenuDao struct {
	internalPandaMenuDao
}

var (
	// PandaMenu is a globally accessible object for table panda_menu operations.
	PandaMenu = pandaMenuDao{
		internal.NewPandaMenuDao(),
	}
)

// Add your custom methods and functionality below.
